# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#写的
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 416)
        #MainWindow.setStyleSheet("#MainWindow{background-image:url(./picture/3.jpg);}")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        #改了
        self.pushButton_11 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_11.setMaximumSize(QtCore.QSize(500, 120))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_4.addWidget(self.pushButton_11, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 3, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(149, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(133, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 5, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.label_4.setMaximumSize(QtCore.QSize(250,100))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150,50))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        #改了
        self.pushButton = QtWidgets.QToolButton(self.page)
        self.pushButton.setObjectName("pushButton")
        #改了
        self.pushButton.setMaximumSize(QtCore.QSize(250, 150))
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        #改了
        self.pushButton_2 = QtWidgets.QToolButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_2.setMaximumSize(QtCore.QSize(350, 150))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 7, 0, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 40))
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_24 = QtWidgets.QLabel(self.page_4)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 230))
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 2, 0, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.page_4)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 3, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setMinimumSize(QtCore.QSize(200, 50))
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 0, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_2.setMinimumSize(QtCore.QSize(250, 50))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.setStyleSheet('''font-size:18px;''') 
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_2, 0, 2, 1, 2)
        #改了
        self.pushButton_13 = QtWidgets.QToolButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 150))
        
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_9.addWidget(self.pushButton_13, 1, 1, 1, 2)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setMinimumSize(QtCore.QSize(0, 60))
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.page_5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #改了
        self.pushButton_7 = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_7.setMaximumSize(QtCore.QSize(270, 270))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        #改了
        self.pushButton_9 = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_9.setMaximumSize(QtCore.QSize(270, 270))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        #改了
        self.pushButton_10 = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_10.setMaximumSize(QtCore.QSize(270, 270))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        #改了
        self.pushButton_8 = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_8.setMaximumSize(QtCore.QSize(270, 270))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.gridLayout_5.addWidget(self.splitter, 2, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setMinimumSize(QtCore.QSize(0, 100))
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        #改了
        self.pushButton_12 = QtWidgets.QToolButton(self.page_2)
        self.pushButton_12.setMaximumSize(QtCore.QSize(350, 100))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        #改了
        self.pushButton_3 = QtWidgets.QToolButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 80))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 6, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.page_2)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        #改
        
        self.pushButton_4 = QtWidgets.QToolButton(self.page_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setMaximumSize(QtCore.QSize(350, 150))
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 8, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setMinimumSize(QtCore.QSize(0, 30))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(250, 50))
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(11111111, 50))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        #改了
        self.pushButton_5 = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        #改了
        self.pushButton_5.setMinimumSize(QtCore.QSize(170, 70))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 5, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem10, 1, 0, 1, 1)
        #改了
        self.pushButton_6 = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 80))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 1, 1, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.page_3)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet('''font-size:18px;''')                    
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_7.addWidget(self.comboBox, 0, 2, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_7, 6, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 2, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_2.addWidget(self.treeWidget_2, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.pushButton_6.clicked.connect(MainWindow.p2p_static_analyse)
        self.pushButton_5.clicked.connect(MainWindow.choose_pcap1)
        self.pushButton.clicked.connect(MainWindow.choose_pcap2)
        self.pushButton_3.clicked.connect(MainWindow.choose_device)
        self.pushButton_4.clicked.connect(MainWindow.change_button4)
        self.pushButton_11.clicked.connect(MainWindow.change_rule)
        self.pushButton_12.clicked.connect(MainWindow.change_rule)
        self.pushButton_2.clicked.connect(MainWindow.pool_static_analyse)
        self.pushButton_7.clicked.connect(MainWindow.changepage0)
        self.pushButton_8.clicked.connect(MainWindow.changepage1)
        self.pushButton_9.clicked.connect(MainWindow.changepage3)
        self.pushButton_10.clicked.connect(MainWindow.changepage4)
        self.pushButton_13.clicked.connect(MainWindow.p2p_dynamic_analyse)
        self.treeWidget_2.clicked.connect(MainWindow.onclicked)
        self.setWindowTitle('基于流量分析的挖矿木马检测工具')
        self.setWindowIcon(QIcon('./picture/icon.jpg'))
        #隐藏边框，非常丑，无法拖拽，无法放大缩小
        #self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        # 设置窗口透明度
        self.setWindowOpacity(0.9)
        # 设置窗口背景透明
        #self.setAttribute(QtCore.Qt.WA_TranslucentBackground) 
        # 设置左侧treeWidget                
        self.treeWidget_2.setStyleSheet('''color: rgb(255, 255, 255);
                                            background-color: rgb(119, 119, 119);
                                            font-size:20px;
                                            font-weight:700;
                                            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                                            border-top-left-radius:10px;
                                            border-bottom-left-radius:10px;''')
        # 把treeWidget的column名字隐藏
        self.treeWidget_2.setHeaderHidden(1)
        self.treeWidget_2.setExpandsOnDoubleClick(1)
        self.stackedWidget.setStyleSheet('''
                                            border-top-right-radius:10px;
                                            border-bottom-right-radius:10px;
                                            ''')
        #去掉中间的空隙
        self.gridLayout_2.setSpacing(0)
        #设置主页按钮
        self.pushButton_9.setText("捕获网络接口的动态流量\n识别连接矿池的挖矿木马")
        self.pushButton_9.setIcon(QtGui.QIcon(r'./picture/ActivityMonitor-icon.png')) # 设置按钮图标
        self.pushButton_9.setIconSize(QtCore.QSize(150,150)) # 设置图标大小
        self.pushButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon) # 设置按钮形式为上图下文
        self.pushButton_9.setStyleSheet("font:16pt;")

        self.pushButton_7.setText("利用静态pcap包\n检测连接矿池的挖矿木马")
        self.pushButton_7.setIcon(QtGui.QIcon(r'./picture/Console-icon.png')) # 设置按钮图标
        self.pushButton_7.setIconSize(QtCore.QSize(150,150)) # 设置图标大小
        self.pushButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon) # 设置按钮形式为上图下文
        self.pushButton_7.setStyleSheet("font:16pt;")

        self.pushButton_10.setText("利用网络集群的静态pcap包\n检测P2P类型的挖矿网络")
        self.pushButton_10.setIcon(QtGui.QIcon(r'./picture/Preview-icon.png')) # 设置按钮图标
        self.pushButton_10.setIconSize(QtCore.QSize(150,150)) # 设置图标大小
        self.pushButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon) # 设置按钮形式为上图下文
        self.pushButton_10.setStyleSheet("font:16pt;")

        self.pushButton_8.setText("捕获边界网关的动态流量\n检测P2P类型的挖矿网络")
        self.pushButton_8.setIcon(QtGui.QIcon(r'./picture/FeedbackAssistant-icon.png')) # 设置按钮图标
        self.pushButton_8.setIconSize(QtCore.QSize(150,150)) # 设置图标大小
        self.pushButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon) # 设置按钮形式为上图下文
        self.pushButton_8.setStyleSheet("font:16pt;")

        self.pushButton_11.setText("点击以查看或编辑规则集")
        self.pushButton_11.setIcon(QtGui.QIcon(r'./picture/Gear-icon.png')) # 设置按钮图标
        self.pushButton_11.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_11.setStyleSheet("font:18pt;")

        self.pushButton_2.setText("开始静态pcap包检测")
        self.pushButton_2.setIcon(QtGui.QIcon(r'./picture/Start-icon.png')) # 设置按钮图标
        self.pushButton_2.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_2.setStyleSheet("font:18pt;")

        self.pushButton.setText("点击上传pcap包")
        self.pushButton.setIcon(QtGui.QIcon(r'./picture/Upload-Folder-icon.png')) # 设置按钮图标
        self.pushButton.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton.setStyleSheet("font:14pt;")

        self.pushButton_12.setText("点击以查看或编辑规则集")
        self.pushButton_12.setIcon(QtGui.QIcon(r'./picture/Gear-icon.png')) # 设置按钮图标
        self.pushButton_12.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_12.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_12.setStyleSheet("font:18pt;")

        self.pushButton_3.setText("扫描网卡")
        self.pushButton_3.setIcon(QtGui.QIcon(r'./picture/Earth-Scan-icon.png')) # 设置按钮图标
        self.pushButton_3.setIconSize(QtCore.QSize(60,60)) # 设置图标大小
        self.pushButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_3.setStyleSheet("font:16pt;")

        self.pushButton_5.setText("点击上传pcap包")
        self.pushButton_5.setIcon(QtGui.QIcon(r'./picture/Upload-Folder-icon.png')) # 设置按钮图标
        self.pushButton_5.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_5.setStyleSheet("font:16pt;")

        self.pushButton_6.setText("开始分析")
        self.pushButton_6.setIcon(QtGui.QIcon(r'./picture/Start-icon.png')) # 设置按钮图标
        self.pushButton_6.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_6.setStyleSheet("font:18pt;")

        self.pushButton_13.setText("开始捕获流量")
        self.pushButton_13.setIcon(QtGui.QIcon(r'./picture/Start-icon.png')) # 设置按钮图标
        self.pushButton_13.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_13.setStyleSheet("font:18pt;")

        self.pushButton_4.setText("开始检测")
        self.pushButton_4.setIcon(QtGui.QIcon(r'./picture/Start-icon.png'))
        self.pushButton_4.setIconSize(QtCore.QSize(80,80)) # 设置图标大小
        self.pushButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon) # 设置按钮形式为左图右文
        self.pushButton_4.setStyleSheet("font:18pt;")
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">编辑规则</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">基本原理</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">检测开始</span></p></body></html>"))
        #self.pushButton_11.setText(_translate("MainWindow", "点击以查看或编辑规则集"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt\">原理：基于对挖矿木马的流量信息分析，我们总结出规则集</p><p align=\"center\"><span style=\" font-size:18pt\">您也可以通过编辑rules.txt来新增或自定义规则集。</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt\">请提交您的pcap文件：</span></p></body></html>"))
        #self.pushButton.setText(_translate("MainWindow", "点击上传pcap包"))
        #self.pushButton_2.setText(_translate("MainWindow", "开始静态pcap包检测"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">静态矿池挖矿检测</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">基本原理</span></p><p><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">使用说明：</span><span style=\" font-size:18pt; font-weight:600;\">使用本功能需要部署在边界路由器上或网关上！</span></p><p align=\"center\"><span style=\" font-size:18pt; \">为确保精度，请至少打开</span><span style=\" font-size:18pt; font-weight:600;\">一个小时</span><span style=\" font-size:18pt; \">以收集流量</span></p><p align=\"center\"><span style=\" font-size:18pt;\">点击结束收集后，请耐心等待</span></p><p align=\"center\"><span style=\" font-size:18pt;\">我们的软件会对网络中的p2p成份进行聚类，</span></p><p align=\"center\"><span style=\" font-size:18pt;\">并为您筛选p2p挖矿成份</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">检测开始</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt\">请选择要检测的时间段：</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0~1点"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1~2点"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "2~3点"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "3~4点"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "4~5点"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "5~6点"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "6~7点"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "7~8点"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "8~9点"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "9~10点"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "10~11点"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "11~12点"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "12~13点"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "13~14点"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "14~15点"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "15~16点"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "16~17点"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "17~18点"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "18~19点"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "19~20点"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "20~21点"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "21~22点"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "22~23点"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "23~24点"))
        #self.pushButton_13.setText(_translate("MainWindow", "开始捕获流量"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">动态p2p识别</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">基于流量分析的挖矿木马检测系统</span></p></body></html>"))
        #self.pushButton_7.setText(_translate("MainWindow", "利用静态pcap包\n"
#"检测连接矿池的挖矿木马"))
        #self.pushButton_9.setText(_translate("MainWindow", "捕获网络接口的动态流量\n"
#"识别连接矿池的挖矿木马"))
        #self.pushButton_10.setText(_translate("MainWindow", "利用网络集群的静态pcap包\n"
#"检测P2P类型的挖矿网络"))
        #self.pushButton_8.setText(_translate("MainWindow", "捕获边界网关的动态流量\n"
#"检测P2P类型的挖矿网络"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">欢迎使用基于流量分析的挖矿木马检测工具！</p><p align=\"center\"><span style=\" font-size:14pt;\">您可以使用此软件检测计算机中是否存在恶意挖矿木马挖矿的行为</p><p align=\"center\"><span style=\" font-size:14pt;\">运行此软件需要管理员权限或root权限</p><p align=\"center\"><span style=\" font-size:14pt;\">我们提供以下四种功能供您选择：</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">动态矿池挖矿检测</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">基本原理</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">原理：我们将在您提供的网络接口进行流量捕获，</span></p><p align=\"center\"><span style=\" font-size:16pt;\">按照我们定义的规则集加以匹配，</span></p><p align=\"center\"><span style=\" font-size:16pt;\">您也可以通过编辑rules.txt来新增或自定义规则集。</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">编辑规则</span></p></body></html>"))
        #self.pushButton_12.setText(_translate("MainWindow", "点击以查看或编辑规则集"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">网卡选择</span></p></body></html>"))
        #self.pushButton_3.setText(_translate("MainWindow", "扫描网卡"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">检测开始</span></p></body></html>"))
        #self.pushButton_4.setText(_translate("MainWindow", "开始检测"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">静态p2p检测</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">基本原理</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">选择输入</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">选择pcap数据包：</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "选择pcap数据包"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; text-decoration: underline;\">检测开始</span></p></body></html>"))
        #self.pushButton_6.setText(_translate("MainWindow", "开始分析"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">请选择要检测的时间段：</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0~1点"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1~2点"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2~3点"))
        self.comboBox.setItemText(3, _translate("MainWindow", "3~4点"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4~5点"))
        self.comboBox.setItemText(5, _translate("MainWindow", "5~6点"))
        self.comboBox.setItemText(6, _translate("MainWindow", "6~7点"))
        self.comboBox.setItemText(7, _translate("MainWindow", "7~8点"))
        self.comboBox.setItemText(8, _translate("MainWindow", "8~9点"))
        self.comboBox.setItemText(9, _translate("MainWindow", "9~10点"))
        self.comboBox.setItemText(10, _translate("MainWindow", "10~11点"))
        self.comboBox.setItemText(11, _translate("MainWindow", "11~12点"))
        self.comboBox.setItemText(12, _translate("MainWindow", "12~13点"))
        self.comboBox.setItemText(13, _translate("MainWindow", "13~14点"))
        self.comboBox.setItemText(14, _translate("MainWindow", "14~15点"))
        self.comboBox.setItemText(15, _translate("MainWindow", "15~16点"))
        self.comboBox.setItemText(16, _translate("MainWindow", "16~17点"))
        self.comboBox.setItemText(17, _translate("MainWindow", "17~18点"))
        self.comboBox.setItemText(18, _translate("MainWindow", "18~19点"))
        self.comboBox.setItemText(19, _translate("MainWindow", "19~20点"))
        self.comboBox.setItemText(20, _translate("MainWindow", "20~21点"))
        self.comboBox.setItemText(21, _translate("MainWindow", "21~22点"))
        self.comboBox.setItemText(22, _translate("MainWindow", "22~23点"))
        self.comboBox.setItemText(23, _translate("MainWindow", "23~24点"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">原理：我们已经通过机器学习的方法训练出了p2p挖矿网络和正常p2p的边界，</span></p><p align=\"center\"><span style=\" font-size:18pt;\">您只需要提供一个pcap数据包，我们会从中提取p2p流信息，对节点进行聚类</span></p></body></html>"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "功能列表"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "主页"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "检测连接矿池的挖矿木马"))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "静态pcap包检测"))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "动态流量检测"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("MainWindow", "检测p2p类型的挖矿木马"))
        self.treeWidget_2.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "静态pcap包p2p检测"))
        self.treeWidget_2.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "动态流量p2p成份检测"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)




        

